# Generated by Django 4.2.7 on 2023-11-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleByCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('total_sales', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleByCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('total_sales', models.FloatField()),
            ],
        ),
    ]
